#!/usr/bin/env bash
# cd "${0%/*}"
cd "${0%/*}"
echo `pwd`

echo $@

for i in "$@";do
    echo $i
done

for i in 1 2;do
    echo $i
done

ARGS=($@)
i=0
until [ ! $i -lt $# ]
do
   echo ${i}
   echo ${ARGS[$i]}
   i=`expr $i + 1`
done


