#!/usr/bin/env bash

TAG_NAME=$1

main(){
    echo $TAG_NAME
    for tag in `git tag -l ${TAG_NAME}`
    do
        echo $tag

        git tag -d ${tag}
        git push origin :${tag}
    done
}

if [ ! ${TAG_NAME} ]
then
    echo 'UAGE: ./delete_tag <regex:tag_name>'
else
    main
fi
