#!/usr/bin/env bash

case $SYS in
    debian|ubuntu|devuan)
        sudo apt -y install curl git
        ;;
    centos|fedora|rhel|amzn)
        sudo yum -y install curl git
        ;;
    Darwin)
        brew install curl git
        ;;
    *)
        echo '暂时不支持该系统'
        ;;
esac

OS=`curl -L https://raw.githubusercontent.com/wxnacy/wshell/master/bin/base/os | bash`
OSS=(${OS})
SYS=${OSS[0]}
VER=${OSS[1]}


WSHELL_HOME=${HOME}/.wshell

test -d ${WSHELL_HOME} || git clone https://github.com/wxnacy/wshell ${WSHELL_HOME}

BP=~/.bash_profile
if [ -f ~/.profile ];then
    BP=~/.profile
fi

if [[ ! $PATH =~ '.wshell/bin' ]];then
    echo 'WARNING: seems you still have not added 'wshell' to the load path.'
    echo ''
    echo '# Load pyenv automatically by adding'
    echo "# the following to ${BP}:"
    echo 'export PATH="${HOME}/.wshell/bin:$PATH"'
    echo '. ${HOME}/.wshell/bin/conf/.bash_profile'
fi
