#!/usr/bin/env bash

for i in git curl;do
    if [ ! `command -v git` ];then
        echo 'Install Wshell failed'
        echo 'Wshell need git'
        exit 0
    fi
done

WSHELL_HOME=${HOME}/.wshell

test -d ${WSHELL_HOME} || git clone https://github.com/wxnacy/wshell ${WSHELL_HOME}

BP=~/.bash_profile
if [ -f ~/.profile ];then
    BP=~/.profile
fi

if [[ ! $PATH =~ '.wshell/bin' ]];then
    echo 'WARNING: seems you still have not added 'wshell' to the load path.'
    echo ''
    echo '# Load pyenv automatically by adding'
    echo "# the following to ${BP}:"
    echo 'export WSPATH="${HOME}/.wshell"'
    echo 'export PATH="${WSPATH}/bin:$PATH"'
    echo '. ${HOME}/.wshell/conf/system/.bash_profile'
fi
