#!/usr/bin/env bash

OS=`curl -L https://raw.githubusercontent.com/wxnacy/wshell/master/bin/base/os | bash`
OSS=(${OS})
SYS=${OSS[0]}
VER=${OSS[1]}


if [ ! `command -v git` ];then
    if [ ${SYS} == 'centos' ]
    then
        sudo yum -y install git
    elif [ ${SYS} == 'ubuntu' ]
    then
        sudo apt update -y
        sudo apt -y install git
    fi
fi

WSHELL_HOME=${HOME}/.wshell

test -d ${WSHELL_HOME} || git clone https://github.com/wxnacy/wshell ${WSHELL_HOME}

BP=~/.bash_profile
if [ -f ~/.profile ];then
    BP=~/.profile
fi

if [[ ! $PATH =~ '.wshell/bin' ]];then
    echo 'WARNING: seems you still have not added 'wshell' to the load path.'
    echo ''
    echo '# Load pyenv automatically by adding'
    echo "# the following to ${BP}:"
    echo 'export PATH="${HOME}/.wshell/bin:$PATH"'
    echo '. ${HOME}/.wshell/bin/conf/.bash_profile'
fi
