echo 'source ~/.zshrc'
# echo $0 >> /tmp/zshmsg
# echo '.zshrc'
# PS4=$'\\\011%D{%s%6.}\011%x\011%I\011%N\011%e\011'
# exec 3>&2 2>/tmp/zshstart.$$.log
# setopt xtrace prompt_subst
export ZSH=${HOME}/.oh-my-zsh

# https://github.com/robbyrussell/oh-my-zsh/wiki/themes
# ZSH_THEME="fishy"
ZSH_THEME="bureau"
# ZSH_THEME="spaceship"
# source ${HOME}/.oh-my-zsh/themes/bureau.zsh-theme
# fpath=( "$HOME/.zfunctions" $fpath )
plugins=(git python sublime)
source $ZSH/oh-my-zsh.sh

# unsetopt xtrace
# exec 2>&3 3>&-

if [ -f ~/.bash_profile ]; then
    source ~/.bash_profile
fi
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
# autoload -U promptinit; promptinit

# autosuggestions
if [ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if [ -f ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# prompt spaceship
colorls_sh=$(dirname $(gem which colorls))/tab_complete.sh
if [ -f $colorls_sh ]; then
    source $colorls_sh
fi
